# Generated by Django 4.2.3 on 2023-07-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data_ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_candidato', models.CharField(max_length=100, verbose_name='Nome')),
                ('experiencia_candidato', models.CharField(max_length=10000, verbose_name='Experiencia')),
                ('email_candidato', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha_candidato', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data_ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome')),
                ('email_empresa', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha_empresa', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data_ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_vaga', models.CharField(max_length=200, verbose_name='Nome')),
                ('faixa_salarial', models.IntegerField(choices=[('até_1000', 'Até 1.000'), ('1000_a_2000', 'De 1.000 a 2.000'), ('2000_a_3000', 'De 2.000 a 3.000'), ('acima_de_3000', 'Acima de 3.000')])),
                ('requisitos', models.CharField(max_length=10000, verbose_name='Requisitos')),
                ('escolaridade', models.CharField(choices=[('ensino_medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('ensino_superior', 'Ensino Superior'), ('pos_mba_mestrado', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='vaga_candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data_ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
