# Generated by Django 4.2.3 on 2023-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='data_ativo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='data_ativo',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='data_ativo',
        ),
        migrations.RemoveField(
            model_name='vaga_candidato',
            name='data_ativo',
        ),
    ]
