# Generated by Django 4.2.3 on 2023-07-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vaga_escolaridade_alter_vaga_faixa_salarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email_candidato',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_empresa',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
