# Generated by Django 4.2.3 on 2023-07-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_last_login_empresa_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='password',
        ),
    ]
