# Generated by Django 4.2.3 on 2023-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_last_login_empresa_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
