# Generated by Django 4.2.3 on 2023-08-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_candidato_last_login_candidato_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaga_candidato',
            unique_together={('vaga', 'candidato')},
        ),
    ]
