# Generated by Django 4.2.3 on 2023-08-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vaga_candidato_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
