# Generated by Django 4.2.3 on 2023-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_candidato_pretensao_salarial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('ensino_medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('ensino_superior', 'Ensino Superior'), ('pos_mba_mestrado', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], default=1, max_length=17),
            preserve_default=False,
        ),
    ]
