# Generated by Django 4.2.3 on 2023-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_candidato_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.CharField(choices=[('até_1000', 'Até 1.000'), ('1000_a_2000', 'De 1.000 a 2.000'), ('2000_a_3000', 'De 2.000 a 3.000'), ('acima_de_3000', 'Acima de 3.000')], max_length=14),
        ),
    ]
